const {readFileSync}=require('node:fs'),vm=require('node:vm'),{test}=require('node:test'),assert=require('node:assert/strict');
function load(at='2026-09-09T12:00:00Z'){
 class Clock extends Date{constructor(...args){super(...(args.length?args:[at]))}static now(){return new Date(at).getTime()}}
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',disabled:false,setAttribute(){}});return nodes.get(id)};
 const scope={URL,BudgetFinance:require('../finance.js'),Intl,Date:Clock,console,localStorage:{getItem:()=>null},document:{querySelector:node,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},setTimeout(){},setInterval(){},matchMedia:()=>({matches:true})};const src=readFileSync(require.resolve('../app.js'),'utf8');vm.runInNewContext(src.slice(0,src.indexOf('  const financeUI = createFinanceUI('))+'globalThis.qa={get state(){return state},set state(s){state=mergeState(s)},blankState,parseBackup,pauseRemaining,wishCapacity,recordWishPurchase,updateNoSpendControl,validateWishlist};})()',scope);return {a:scope.qa,node}
}
const wish=(over={})=>({id:'w',name:'Headphones',amount:80,url:'https://example.com/item',note:'For travelling',createdAt:'2026-09-06T12:00:00Z',status:'waiting',...over});
const setup=(a,w=wish())=>{const s=a.blankState();s.version=10;s.wishlist=[w];s.paydays=[{id:'p',date:'2026-09-01',amount:1000,name:'Paycheck'}];s.paycheckPlans={p:{savings:200,debt:100,other:0}};s.billAssignments={};a.state=s;return a.state};
test('Legacy v39 backups preserve finances and start with an empty wishlist',()=>{const{a}=load();const s=a.blankState();delete s.wishlist;s.version=10;s.paydays=[{id:'p',date:'2025-12-31',amount:2500}];const r=a.parseBackup(JSON.stringify(s));assert.equal(r.version,11);assert.equal(r.wishlist.length,0);assert.equal(r.paydays[0].date,'2025-12-31')});
test('Pause requires exactly 72 elapsed hours, across a daylight-saving change',()=>{const{a}=load();const w=wish({createdAt:'2026-10-31T12:00:00-04:00'});const end=Date.parse(w.createdAt)+72*3600000;assert.equal(a.pauseRemaining(w,end-1),1);assert.equal(a.pauseRemaining(w,end),0);assert.equal(a.pauseRemaining(w,end+3600000),0)});
test('Wishlist never reserves money; one purchase changes only its paycheck and prevents repeats',()=>{const{a}=load();setup(a);assert.equal(a.wishCapacity(a.state.wishlist[0],'p'),700);const e=a.recordWishPurchase('w','p',true);assert.equal(e.paycheckId,'p');assert.equal(a.wishCapacity(a.state.wishlist[0],'p'),620);assert.equal(a.state.expenses.length,1);assert.equal(a.state.wishlist[0].expenseId,e.id);assert.equal(a.state.wishlist[0].status,'bought');assert.throws(()=>a.recordWishPurchase('w','p',true));assert.equal(a.state.expenses.length,1)});
test('Early, unconfirmed, future and unaffordable purchases reject atomically',()=>{for(const mode of ['early','cash','future','cost','missing']){const{a}=load();setup(a,mode==='early'?wish({createdAt:'2026-09-07T12:00:00Z'}):wish());if(mode==='future')a.state.paydays[0].date='2026-10-01';if(mode==='cost')a.state.wishlist[0].amount=701;const before=JSON.stringify(a.state);assert.throws(()=>a.recordWishPurchase('w',mode==='missing'?'none':'p',mode!=='cash'),mode);assert.equal(JSON.stringify(a.state),before,mode)}});
test('Wishlist backup round-trip preserves timestamps, decisions, links and purchase ID',()=>{const{a}=load();setup(a);a.recordWishPurchase('w','p',true);const restored=a.parseBackup(JSON.stringify(a.state));assert.deepEqual(JSON.stringify(restored.wishlist),JSON.stringify(a.state.wishlist));assert.deepEqual(JSON.parse(JSON.stringify(restored.expenses)),JSON.parse(JSON.stringify(a.state.expenses)));for(const change of [{url:'javascript:alert(1)'},{url:'https://['},{amount:-1},{createdAt:'invalid'},{status:'unknown'}])assert.throws(()=>a.validateWishlist([wish(change)]));assert.throws(()=>a.validateWishlist([wish(),wish()]))});
test('No-spend control remains visible and cannot conflict with expenses or future dates',()=>{const{a,node}=load();a.state=a.blankState();a.updateNoSpendControl('#b','#h','2026-09-09');assert.equal(node('#b').hidden,false);assert.equal(node('#b').disabled,false);a.state.expenses.push({date:'2026-09-09',amount:4});a.updateNoSpendControl('#b','#h','2026-09-09');assert.equal(node('#b').hidden,false);assert.equal(node('#b').disabled,true);a.updateNoSpendControl('#b','#h','2026-10-01');assert.equal(node('#b').disabled,true)});
